name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    # Remove the strategy/matrix for now to simplify
    steps:
    - uses: actions/checkout@v3

    # We skip 'actions/setup-python' and use the EC2's native Python  3
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest

    - name: Run tests
      run: |
        cd src
        python3 -m pytest addition.py
